openapi: 3.0.3
info:
  title: Property Data Trust Framework API
  version: 1.2.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  description: This API defines how participants in the UK Property Data Trust Framework can securely share property data, together with the verifiable provenance of that data. The API is built around a variation of OpenID Connect Verified Claims schema.
servers:
  - url: http://api.pdtf-example.com
    description: Example PDTF data source
tags:
  - name: transactions
    description: Transactions API
paths:
  /transaction/claims:
    parameters:
      - $ref: "#/components/parameters/partnerReferenceId"
      - $ref: "#/components/parameters/uprn"
    get:
      summary: Get a list of claims on a property for a given transaction ID
      tags:
        - transactions
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: https://raw.githubusercontent.com/Property-Data-Trust-Framework/schemas/master/src/schemas/pdtf-verified-claims.json
        "204":
          description: No Content - no claims are available for this property
      operationId: getTransactionClaims
      parameters: []
    post:
      summary: Add claims for a property in a transaction
      tags:
        - transactions
      operationId: addTransactionClaims
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request - the supplied claims contain one or more validation errors
        "401":
          description: Unauthorized
      description: Add one or more new claims for this UPRN
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: https://raw.githubusercontent.com/Property-Data-Trust-Framework/schemas/master/src/schemas/pdtf-verified-claims.json
  /transaction/propertyPack:
    parameters:
      - $ref: "#/components/parameters/partnerReferenceId"
    get:
      summary: Get latest state of data
      tags:
        - transactions
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
                description: JSON representation of property pack information
            text/html:
              schema:
                type: string
                description: HTML renedered property pack information
        "404":
          description: No claims are available for this property
      operationId: getCurrentTransactionState
      description: Retrieve a JSON or HTML representation of the state of the property data when all claims to date are applied.
      parameters: []
  /transaction/{id}/subscribe:
    parameters:
      - $ref: "#/components/parameters/partnerReferencePathId"
    post:
      summary: Create a new webhook subscription for this transaction
      tags:
        - transactions
      operationId: transactionwebhookSubscribe
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                callbackUrl:
                  type: string
                  format: uri
      callbacks:
        newClaims:
          "{$request.body#/callbackUrl}":
            post:
              requestBody:
                required: true
                content:
                  application/json:
                    schema:
                      $ref: https://raw.githubusercontent.com/Property-Data-Trust-Framework/schemas/master/src/schemas/pdtf-verified-claims.json
              responses:
                "200":
                  description: Please send a 200 response to acknowledge the callback and prevent retries
    delete:
      summary: Delete webhook
      tags:
        - transactions
      operationId: transactionwebhookUnsubscribe
      responses:
        "200":
          description: OK
      description: Delete webhook for this UPRN for the current authenticated user, if any
components:
  parameters:
    partnerReferencePathId:
      required: true
      name: id
      in: path
      schema:
        type: string
      description: Unique identifier for the transaction in the partner environment
    partnerReferenceId:
      name: partnerReferenceId
      in: query
      schema:
        type: string
      description: Unique identifier for the transaction in the partner environment
    uprn:
      name: uprn
      in: query
      schema:
        type: string
      description: Unique Property Reference Number
